# Generated by Django 3.2 on 2021-06-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1_simbathon5', '0003_auto_20210624_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content_type', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('write_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QNA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content_type', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('write_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
